/**
 * Sample articles seed for demo/testing purposes
 */
import { drizzle } from "drizzle-orm/postgres-js";
import { articles, newsAgencies } from "../drizzle/schema";
import { sql } from "drizzle-orm";

const db = drizzle(process.env.DATABASE_URL!);

const SAMPLE_ARTICLES = [
  // WAR/CONFLICT
  { title: "Israeli Air Force Conducts Strikes on Southern Lebanon", titleAr: "سلاح الجو الإسرائيلي ينفذ ضربات في جنوب لبنان", summary: "Israeli warplanes struck multiple targets in southern Lebanon following rocket fire from Hezbollah positions near the border town of Khiam.", content: "Israeli warplanes conducted a series of airstrikes on southern Lebanon on Monday, targeting what military officials described as Hezbollah weapons depots and launch sites. The strikes came in response to a barrage of rockets fired into northern Israel earlier in the day. Lebanese health officials reported at least three casualties in the strikes. The Israeli military said it struck 'terror infrastructure' and warned of further action if attacks continued.", topics: ["WAR/CONFLICT", "SECURITY"], country: "Lebanon", region: "MENA", sentiment: "negative", sentimentScore: -0.8, isBreaking: true, latitude: 33.27, longitude: 35.2, agencyName: "Al Arabiya" },
  { title: "Houthi Forces Launch Drone Attack on Saudi Oil Infrastructure", titleAr: "قوات الحوثيين تشن هجوماً بالطائرات المسيّرة على البنية التحتية النفطية السعودية", summary: "Yemen's Houthi rebels claimed responsibility for drone attacks targeting Saudi Aramco facilities in the Eastern Province.", content: "Yemen's Iran-backed Houthi movement launched a wave of drone attacks targeting oil infrastructure in Saudi Arabia's Eastern Province on Sunday. Saudi Aramco confirmed that its Abqaiq processing facility was targeted but said operations continued normally. The attack was the latest in a series of cross-border strikes that have escalated tensions in the region. Saudi air defense systems intercepted several of the drones before they reached their targets.", topics: ["WAR/CONFLICT", "ENERGY"], country: "Saudi Arabia", region: "MENA", sentiment: "negative", sentimentScore: -0.9, isBreaking: true, latitude: 25.93, longitude: 49.67, agencyName: "Saudi Press Agency (SPA)" },
  { title: "US Deploys Additional Forces to Al-Udeid Base Amid Regional Tensions", titleAr: "الولايات المتحدة تنشر قوات إضافية في قاعدة العديد وسط التوترات الإقليمية", summary: "The Pentagon announced the deployment of additional troops and aircraft to Al-Udeid Air Base in Qatar as a precautionary measure.", content: "The United States military announced Monday the deployment of additional forces to Al-Udeid Air Base in Qatar, citing the need to bolster regional deterrence amid heightened tensions. The deployment includes F-35 fighter jets and additional ground personnel. Pentagon spokesperson said the move was a 'prudent precaution' and not a response to any specific threat. Qatar's defense ministry welcomed the deployment as part of ongoing bilateral security cooperation.", topics: ["WAR/CONFLICT", "DIPLOMACY"], country: "Qatar", region: "MENA", sentiment: "negative", sentimentScore: -0.5, isBreaking: false, latitude: 25.12, longitude: 51.31, agencyName: "Al Jazeera English" },
  { title: "Syrian Forces Advance in Idlib Province After Ceasefire Collapse", titleAr: "القوات السورية تتقدم في محافظة إدلب بعد انهيار وقف إطلاق النار", summary: "Syrian government forces backed by Russian air support resumed offensive operations in Idlib province following the breakdown of a ceasefire agreement.", content: "Syrian government forces, supported by Russian airstrikes, resumed their offensive in Idlib province after a ceasefire brokered by Turkey collapsed. The renewed fighting has displaced thousands of civilians in the region. The UN Office for the Coordination of Humanitarian Affairs warned of a potential humanitarian catastrophe as winter approaches. Turkey, which backs opposition groups in the area, called for an immediate halt to hostilities.", topics: ["WAR/CONFLICT", "HUMANITARIAN"], country: "Syria", region: "MENA", sentiment: "negative", sentimentScore: -0.85, isBreaking: false, latitude: 35.93, longitude: 36.63, agencyName: "Al Jazeera" },
  { title: "Iran-Backed Militias Attack US Base in Iraq with Rockets", titleAr: "الميليشيات المدعومة من إيران تهاجم قاعدة أمريكية في العراق بالصواريخ", summary: "Iran-aligned militias fired rockets at Ain Assad Air Base in western Iraq, wounding two US service members.", content: "Iran-aligned militias fired a salvo of rockets at Ain Assad Air Base in western Iraq late Tuesday, wounding two American service members and damaging equipment. The attack was claimed by the Islamic Resistance in Iraq, an umbrella group of Iranian-backed factions. US forces returned fire, targeting militia positions. The incident comes amid heightened tensions following US strikes on militia targets in Syria and Iraq.", topics: ["WAR/CONFLICT", "SECURITY"], country: "Iraq", region: "MENA", sentiment: "negative", sentimentScore: -0.9, isBreaking: true, latitude: 33.38, longitude: 42.44, agencyName: "Reuters Middle East" },

  // ECONOMY
  { title: "Saudi Aramco Reports Record Quarterly Profits Amid High Oil Prices", titleAr: "أرامكو السعودية تسجل أرباحاً فصلية قياسية في ظل ارتفاع أسعار النفط", summary: "Saudi Aramco announced quarterly net income of $35 billion, driven by elevated crude oil prices and strong global demand.", content: "Saudi Aramco, the world's largest oil company, reported quarterly net income of $35 billion, surpassing analyst expectations. The results were driven by Brent crude prices averaging above $85 per barrel during the quarter. CEO Amin Nasser said the company was well-positioned to meet growing global energy demand. Aramco also announced plans to increase its capital expenditure to expand production capacity to 12.3 million barrels per day.", topics: ["ECONOMY", "ENERGY"], country: "Saudi Arabia", region: "MENA", sentiment: "positive", sentimentScore: 0.8, isBreaking: false, latitude: 26.27, longitude: 50.15, agencyName: "Arab News" },
  { title: "UAE Launches $10 Billion Green Energy Investment Fund", titleAr: "الإمارات تطلق صندوقاً للاستثمار في الطاقة الخضراء بقيمة 10 مليارات دولار", summary: "The UAE announced a major green energy investment fund targeting renewable projects across the MENA region ahead of COP30.", content: "The United Arab Emirates launched a $10 billion green energy investment fund on Wednesday, targeting solar, wind, and hydrogen projects across the Middle East and North Africa. The fund, managed by Abu Dhabi's Masdar, will focus on projects in Egypt, Morocco, Jordan, and Saudi Arabia. UAE Energy Minister Suhail Al Mazrouei said the initiative was part of the country's commitment to achieving net-zero emissions by 2050.", topics: ["ECONOMY", "ENERGY", "TECHNOLOGY"], country: "UAE", region: "MENA", sentiment: "positive", sentimentScore: 0.75, isBreaking: false, latitude: 24.47, longitude: 54.37, agencyName: "The National" },
  { title: "Egypt's IMF Loan Program Faces Challenges as Pound Weakens", titleAr: "برنامج قرض صندوق النقد الدولي لمصر يواجه تحديات مع تراجع الجنيه", summary: "Egypt's currency has fallen to record lows against the dollar, complicating the country's $8 billion IMF bailout program.", content: "Egypt's pound fell to a record low of 48 per US dollar this week, raising concerns about the country's ability to meet IMF program targets. The currency has lost more than 50% of its value since the start of the year as the country grapples with a severe foreign currency shortage. The IMF is expected to review Egypt's progress under its $8 billion extended fund facility program next month. Analysts warn that further devaluation could trigger social unrest.", topics: ["ECONOMY", "POLITICS"], country: "Egypt", region: "MENA", sentiment: "negative", sentimentScore: -0.6, isBreaking: false, latitude: 30.04, longitude: 31.23, agencyName: "Egypt Independent" },
  { title: "Qatar Signs $20 Billion LNG Supply Deal with Germany", titleAr: "قطر توقع صفقة لتوريد الغاز الطبيعي المسال بقيمة 20 مليار دولار مع ألمانيا", summary: "QatarEnergy and Germany's SEFE signed a 15-year LNG supply agreement, marking a major energy partnership.", content: "QatarEnergy signed a landmark 15-year liquefied natural gas supply agreement with Germany's SEFE, worth approximately $20 billion. The deal will see Qatar supply 2 million tonnes of LNG per year to Germany starting in 2026. The agreement is part of Germany's effort to diversify away from Russian natural gas. Qatari Energy Minister Saad Al-Kaabi called it 'a testament to the reliability and importance of Qatari energy to European security'.", topics: ["ECONOMY", "ENERGY", "DIPLOMACY"], country: "Qatar", region: "MENA", sentiment: "positive", sentimentScore: 0.7, isBreaking: false, latitude: 25.29, longitude: 51.53, agencyName: "Al Jazeera English" },

  // POLITICS
  { title: "Saudi Arabia and Iran Restore Full Diplomatic Relations", titleAr: "المملكة العربية السعودية وإيران تستعيدان العلاقات الدبلوماسية الكاملة", summary: "Saudi Arabia and Iran have officially reopened their embassies and restored full diplomatic ties after years of hostility.", content: "Saudi Arabia and Iran officially restored full diplomatic relations, with both countries reopening their embassies in Riyadh and Tehran. The normalization, brokered by China in March 2023, marks a significant shift in regional dynamics. Saudi Foreign Minister Prince Faisal bin Farhan met his Iranian counterpart Hossein Amir-Abdollahian in Riyadh for the first time in seven years. Both sides pledged to cooperate on regional stability and economic ties.", topics: ["POLITICS", "DIPLOMACY"], country: "Saudi Arabia", region: "MENA", sentiment: "positive", sentimentScore: 0.85, isBreaking: false, latitude: 24.69, longitude: 46.72, agencyName: "Al Arabiya" },
  { title: "Turkey Holds Snap Elections Amid Economic Crisis", titleAr: "تركيا تجري انتخابات مبكرة وسط الأزمة الاقتصادية", summary: "Turkish President Erdogan called snap parliamentary elections as the country faces its worst economic crisis in decades.", content: "Turkish President Recep Tayyip Erdogan announced snap parliamentary elections to be held in six weeks, as Turkey faces soaring inflation of over 65% and a weakening lira. The opposition CHP party said it was ready for elections and called for a return to orthodox economic policies. International observers expressed concern about the fairness of the electoral process given recent restrictions on media freedom.", topics: ["POLITICS", "ECONOMY"], country: "Turkey", region: "MENA", sentiment: "negative", sentimentScore: -0.4, isBreaking: false, latitude: 39.93, longitude: 32.86, agencyName: "Hurriyet Daily News" },
  { title: "Israeli-Palestinian Peace Talks Resume in Cairo", titleAr: "محادثات السلام الإسرائيلية الفلسطينية تستأنف في القاهرة", summary: "US-brokered peace talks between Israeli and Palestinian negotiators resumed in Cairo with Egypt and Qatar as mediators.", content: "US-brokered negotiations between Israeli and Palestinian representatives resumed in Cairo, with Egyptian and Qatari officials serving as mediators. The talks focus on a potential hostage deal and a temporary ceasefire in Gaza. A senior US official said both sides had shown 'some flexibility' but significant gaps remain. Hamas political bureau chief Ismail Haniyeh said the movement was open to a deal that included a permanent end to hostilities.", topics: ["POLITICS", "DIPLOMACY"], country: "Egypt", region: "MENA", sentiment: "mixed", sentimentScore: 0.1, isBreaking: false, latitude: 30.04, longitude: 31.23, agencyName: "Middle East Eye" },

  // TECHNOLOGY
  { title: "Saudi Arabia Launches $40 Billion AI Investment Initiative", titleAr: "المملكة العربية السعودية تطلق مبادرة استثمارية في الذكاء الاصطناعي بقيمة 40 مليار دولار", summary: "Saudi Arabia's Public Investment Fund announced a massive AI investment program targeting global technology companies.", content: "Saudi Arabia's Public Investment Fund announced a $40 billion artificial intelligence investment initiative, making it one of the largest AI investment programs globally. The fund will invest in leading AI companies in the US, Asia, and Europe, while also funding domestic AI infrastructure including data centers and research facilities. Crown Prince Mohammed bin Salman said AI was central to Vision 2030's goal of diversifying the Saudi economy.", topics: ["TECHNOLOGY", "ECONOMY"], country: "Saudi Arabia", region: "MENA", sentiment: "positive", sentimentScore: 0.8, isBreaking: false, latitude: 24.69, longitude: 46.72, agencyName: "Arab News" },
  { title: "Iran Expands Cyber Operations Targeting Gulf State Infrastructure", titleAr: "إيران توسع عملياتها الإلكترونية التي تستهدف البنية التحتية لدول الخليج", summary: "US and UK cybersecurity agencies issued a joint advisory warning of increased Iranian cyber attacks on critical infrastructure.", content: "The US Cybersecurity and Infrastructure Security Agency and UK's NCSC issued a joint advisory warning of escalating Iranian cyber operations targeting critical infrastructure in Gulf states and Israel. The advisory identified a group linked to Iran's IRGC as responsible for attacks on water treatment facilities, power grids, and financial institutions. Several Gulf states reported disruptions to government services following the attacks.", topics: ["TECHNOLOGY", "SECURITY"], country: "Iran", region: "MENA", sentiment: "negative", sentimentScore: -0.7, isBreaking: true, latitude: 35.7, longitude: 51.4, agencyName: "Times of Israel" },

  // ENERGY
  { title: "OPEC+ Agrees to Extend Production Cuts Through End of Year", titleAr: "أوبك+ توافق على تمديد تخفيضات الإنتاج حتى نهاية العام", summary: "OPEC+ members agreed to maintain current oil production cuts of 3.66 million barrels per day through December.", content: "OPEC+ members meeting in Vienna agreed to extend current oil production cuts of 3.66 million barrels per day through the end of the year. Saudi Arabia and Russia, the group's de facto leaders, pushed for the extension amid concerns about weakening global demand. Oil prices rose 2% following the announcement, with Brent crude trading above $87 per barrel. The decision was unanimous, with all 23 member countries agreeing to the extension.", topics: ["ENERGY", "ECONOMY"], country: "Saudi Arabia", region: "MENA", sentiment: "positive", sentimentScore: 0.5, isBreaking: false, latitude: 24.69, longitude: 46.72, agencyName: "Reuters Middle East" },
  { title: "Egypt Discovers Major Natural Gas Field in Mediterranean", titleAr: "مصر تكتشف حقلاً ضخماً للغاز الطبيعي في البحر المتوسط", summary: "Egypt's state oil company announced the discovery of a significant natural gas field in the Mediterranean Sea with estimated reserves of 5 trillion cubic feet.", content: "Egypt's state oil company EGPC announced the discovery of a major natural gas field in the Mediterranean Sea, with preliminary estimates suggesting reserves of 5 trillion cubic feet. The discovery, made in partnership with Italian energy company ENI, is located 80 kilometers off the coast of Alexandria. Energy Minister Tarek El-Molla called it 'a game-changer for Egypt's energy security and export potential'. Production is expected to begin within three years.", topics: ["ENERGY", "ECONOMY"], country: "Egypt", region: "MENA", sentiment: "positive", sentimentScore: 0.85, isBreaking: false, latitude: 31.2, longitude: 29.9, agencyName: "Egypt Independent" },

  // HUMANITARIAN
  { title: "UN Warns of Catastrophic Famine Risk in Yemen as Aid Funding Dries Up", titleAr: "الأمم المتحدة تحذر من خطر مجاعة كارثية في اليمن مع نضوب تمويل المساعدات", summary: "The UN World Food Programme warned that 17 million Yemenis face acute food insecurity as international aid funding falls short.", content: "The United Nations World Food Programme warned that 17 million people in Yemen face acute food insecurity, with 5 million on the brink of famine. The agency said it had received only 30% of the funding needed for its Yemen operations this year, forcing it to cut rations for millions of beneficiaries. WFP Executive Director Cindy McCain called on international donors to urgently increase contributions, warning that 'every day of delay costs lives'.", topics: ["HUMANITARIAN", "WAR/CONFLICT"], country: "Yemen", region: "MENA", sentiment: "negative", sentimentScore: -0.9, isBreaking: false, latitude: 15.47, longitude: 44.22, agencyName: "Middle East Eye" },
  { title: "Lebanon Economic Crisis Deepens as Banks Restrict Withdrawals", titleAr: "الأزمة الاقتصادية اللبنانية تتعمق مع تقييد البنوك للسحوبات", summary: "Lebanese banks further restricted dollar withdrawals as the country's economic collapse enters its fifth year.", content: "Lebanese banks further tightened restrictions on dollar withdrawals, limiting customers to $200 per month as the country's economic crisis deepens. The Lebanese pound has lost over 98% of its value since 2019, and the country's banking system has effectively collapsed. The World Bank estimates that Lebanon's economic crisis is one of the worst in modern history. Protests erupted outside several bank branches in Beirut as frustrated depositors demanded access to their savings.", topics: ["ECONOMY", "HUMANITARIAN"], country: "Lebanon", region: "MENA", sentiment: "negative", sentimentScore: -0.85, isBreaking: false, latitude: 33.89, longitude: 35.5, agencyName: "L'Orient Today" },

  // SECURITY
  { title: "Israel Intercepts Iranian Ballistic Missiles Over Red Sea", titleAr: "إسرائيل تعترض صواريخ باليستية إيرانية فوق البحر الأحمر", summary: "Israel's Arrow missile defense system successfully intercepted a salvo of Iranian ballistic missiles fired from Yemen.", content: "Israel's Arrow-3 missile defense system intercepted a salvo of ballistic missiles fired from Yemen by Houthi forces acting on behalf of Iran, the Israeli military announced. The interceptions took place over the Red Sea. No casualties or damage were reported in Israel. The incident marks the first time Israel's Arrow system has been used in active combat. Defense Minister Yoav Gallant praised the performance of the system and warned Iran of 'severe consequences' for further attacks.", topics: ["SECURITY", "WAR/CONFLICT"], country: "Israel", region: "MENA", sentiment: "negative", sentimentScore: -0.7, isBreaking: true, latitude: 31.5, longitude: 34.75, agencyName: "The Jerusalem Post" },
  { title: "Saudi Arabia Arrests 15 Terror Suspects Linked to Iran", titleAr: "السعودية تعتقل 15 مشتبهاً بالإرهاب مرتبطين بإيران", summary: "Saudi security forces arrested 15 suspects accused of planning attacks on government facilities and oil infrastructure on behalf of Iran.", content: "Saudi Arabia's Presidency of State Security announced the arrest of 15 suspects accused of planning terrorist attacks on government facilities and oil infrastructure. Officials said the suspects had received training and funding from Iran's Islamic Revolutionary Guard Corps. The arrests were made in multiple cities including Riyadh, Jeddah, and Dammam. Saudi Interior Minister Prince Abdulaziz bin Saud said the kingdom would 'not tolerate any threat to its security and stability'.", topics: ["SECURITY", "POLITICS"], country: "Saudi Arabia", region: "MENA", sentiment: "negative", sentimentScore: -0.6, isBreaking: false, latitude: 24.69, longitude: 46.72, agencyName: "Saudi Press Agency (SPA)" },

  // DIPLOMACY
  { title: "Abraham Accords: Morocco and Israel Expand Economic Ties", titleAr: "اتفاقيات أبراهام: المغرب وإسرائيل يوسعان العلاقات الاقتصادية", summary: "Morocco and Israel signed a series of bilateral agreements covering trade, technology, and agricultural cooperation.", content: "Morocco and Israel signed a comprehensive package of bilateral agreements during a high-level meeting in Rabat, expanding economic and technological cooperation under the Abraham Accords framework. The agreements cover trade facilitation, agricultural technology transfer, cybersecurity cooperation, and tourism promotion. Israeli Prime Minister Benjamin Netanyahu called Morocco 'a true partner for peace and prosperity'. The two countries have seen bilateral trade grow by 400% since normalization in 2020.", topics: ["DIPLOMACY", "ECONOMY"], country: "Morocco", region: "MENA", sentiment: "positive", sentimentScore: 0.75, isBreaking: false, latitude: 33.99, longitude: -6.85, agencyName: "Morocco World News" },
  { title: "China Mediates Sudan Peace Talks in Beijing", titleAr: "الصين تتوسط في محادثات السلام السودانية في بكين", summary: "China hosted talks between Sudan's warring factions, the SAF and RSF, in an attempt to broker a ceasefire.", content: "China hosted a new round of peace talks between Sudan's warring factions — the Sudanese Armed Forces and the Rapid Support Forces — in Beijing. Chinese Special Envoy for African Affairs Liu Guijin chaired the talks, which focused on a humanitarian ceasefire and the protection of civilians. The conflict, which erupted in April 2023, has killed tens of thousands and displaced over 8 million people. The African Union and Arab League also participated as observers.", topics: ["DIPLOMACY", "HUMANITARIAN"], country: "Sudan", region: "MENA", sentiment: "mixed", sentimentScore: 0.2, isBreaking: false, latitude: 15.55, longitude: 32.53, agencyName: "Radio Dabanga" },
];

async function seedArticles() {
  console.log("📰 Seeding sample articles...");
  
  // Get agency IDs
  const agencyList = await db.select({ id: newsAgencies.id, name: newsAgencies.name }).from(newsAgencies).limit(200);
  const agencyMap = new Map(agencyList.map(a => [a.name, a.id]));
  
  let count = 0;
  const now = new Date();
  
  for (let i = 0; i < SAMPLE_ARTICLES.length; i++) {
    const art = SAMPLE_ARTICLES[i];
    const agencyId = agencyMap.get(art.agencyName) || agencyList[0]?.id || 1;
    const publishedAt = new Date(now.getTime() - (i * 2 * 60 * 60 * 1000)); // Spread over last 40 hours
    
    try {
      await db.insert(articles).values({
        title: art.title,
        titleAr: art.titleAr,
        summary: art.summary,
        content: art.content,
        url: `https://example.com/article-${i + 1}`,
        agencyId,
        topics: art.topics,
        country: art.country,
        region: art.region,
        sentiment: art.sentiment as any,
        sentimentScore: art.sentimentScore,
        isBreaking: art.isBreaking,
        publishedAt,
        author: ['Staff Reporter', 'Correspondent', 'Bureau Chief', 'Senior Editor'][i % 4],
        language: 'en',
        imageUrl: null,
      });
      count++;
    } catch (e: any) {
      console.warn(`  ⚠️  Article "${art.title.substring(0, 40)}...": ${e.message}`);
    }
  }
  
  console.log(`✅ Seeded ${count} sample articles`);
  process.exit(0);
}

seedArticles().catch(e => { console.error("❌ Seed failed:", e); process.exit(1); });
